import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed Background */}
        <div
          className="
            fixed inset-0
            bg-[url('/assets/background-image.svg')]
            bg-cover bg-center bg-no-repeat
            opacity-40
            -z-10
          "
        />

        {/* Foreground Content */}
        <div className="relative z-10 min-h-screen font-sans">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
